-- MySQL Script generated by MySQL Workbench
-- Fri Nov 11 18:26:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema conociendocordoba
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `conociendocordoba` ;

-- -----------------------------------------------------
-- Schema conociendocordoba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conociendocordoba` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `conociendocordoba` ;

-- -----------------------------------------------------
-- Table `administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administrador` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `administrador` (
  `idadministrador` INT NOT NULL AUTO_INCREMENT,
  `Mail` VARCHAR(150) NOT NULL,
  `Contraseña` VARCHAR(150) NOT NULL,
  `idbeneficio` INT NOT NULL,
  PRIMARY KEY (`idadministrador`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `beneficio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beneficio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `beneficio` (
  `idbeneficio` INT NOT NULL AUTO_INCREMENT,
  `DetalleBeneficio` TEXT(200) NOT NULL,
  `fechavencimiento` DATETIME(6) NOT NULL,
  `idregistro` INT NOT NULL,
  PRIMARY KEY (`idbeneficio`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `registro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `registro` (
  `idregistro` INT NOT NULL AUTO_INCREMENT,
  `Nombre_y_Apellido_usuario` VARCHAR(150) NOT NULL,
  `Mail` VARCHAR(150) NOT NULL,
  `Contraseña` VARCHAR(150) NOT NULL,
  `id_usu` INT NOT NULL,
  PRIMARY KEY (`idregistro`, `id_usu`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Apellido` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
