-- MySQL Script generated by MySQL Workbench
-- Fri Nov 11 17:47:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema conociendocordoba
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `conociendocordoba` ;

-- -----------------------------------------------------
-- Schema conociendocordoba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conociendocordoba` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `conociendocordoba` ;

-- -----------------------------------------------------
-- Table `administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administrador` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `administrador` (
  `idadministrador` INT NOT NULL AUTO_INCREMENT,
  `Mail` VARCHAR(150) NOT NULL,
  `Contraseña` VARCHAR(150) NOT NULL,
  `idvisitante` INT NOT NULL,
  PRIMARY KEY (`idadministrador`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `visitante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `visitante` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `visitante` (
  `idvisitante` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NOT NULL,
  `Mail` VARCHAR(150) NOT NULL,
  `Mail` VARCHAR(150) NOT NULL,
  `Mensaje` TEXT(200) NOT NULL,
  `administrador_idadministrador` INT NOT NULL,
  PRIMARY KEY (`idvisitante`, `administrador_idadministrador`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
