# Generated by Django 4.2.1 on 2023-06-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.AutoField(db_column='idCarrito', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('preciounitario', models.IntegerField(db_column='PrecioUnitario')),
                ('preciototal', models.IntegerField(db_column='PrecioTotal')),
            ],
            options={
                'db_table': 'carrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('idciudad', models.AutoField(db_column='idCiudad', primary_key=True, serialize=False)),
                ('nombreciudad', models.CharField(db_column='NombreCiudad', max_length=150)),
            ],
            options={
                'db_table': 'ciudades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('idfactura', models.AutoField(db_column='idFactura', primary_key=True, serialize=False)),
                ('fechafactura', models.DateField(db_column='FechaFactura')),
                ('montototal', models.IntegerField(db_column='MontoTotal')),
            ],
            options={
                'db_table': 'facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historialcompras',
            fields=[
                ('idhistorial', models.AutoField(db_column='idHistorial', primary_key=True, serialize=False)),
                ('fechacompra', models.DateField(db_column='FechaCompra')),
                ('preciounitario', models.IntegerField(db_column='PrecioUnitario')),
                ('preciototal', models.IntegerField(db_column='PrecioTotal')),
                ('estado', models.CharField(db_column='Estado', max_length=10)),
            ],
            options={
                'db_table': 'historialcompras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(db_column='NombreProducto', max_length=150)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=500)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('precio', models.IntegerField(db_column='Precio')),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
    ]
